### ISSUE TITLE
Definir url do novo site do DNAD

### ISSUE THREAD

**Issue by giggio** [dotnetarchitects/dnad#11]
Configurar CNAME de dnad.dotnetarchitects.net

**Comment by giggio** [comment]
Estou arrumando isso. Vejam aqui o que vou fazer: https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/

**Comment by giggio** [comment]
Feito. Já posso mudar o DNS quando quisermos. Acabei de testar alterando meus hosts file.
Se quiserem testar, é só colocar no hosts:

```
199.27.76.133 dnad.dotnetarchitects.net
```

Se não funcionar o IP pode ter mudado, verifiquem o ip de dotnetarchitects.github.io.

Quando estiver em um ponto que quisermos virar a chave me avisem.

**Comment by giggio** [comment]
Fechado no commit e7ff0cfbd617821d434a71009c58a36649e1be37.

**Comment by brenoferreira** [comment]
@giggio pode mudar o DNS

**Comment by giggio** [comment]
No ar: http://dnad.dotnetarchitects.net/
Vou desligar o servidor da Lambda3 que atendia o site, ok?

**Comment by brenoferreira** [comment]
:+1: Valeu @giggio 
Pode desligar
