### ISSUE TITLE
proposta - novo layout

### ISSUE THREAD

**Issue by MayogaX** [dotnetarchitects/dnad#13]
Estava pensando, e em 2015 podia ter um novo layout pro site, não? 
Se derem um comentário dizendo que aceitam que eu tente eu vou mandar pull request disso depois de um tempinho.

Que acham?

**Comment by egomesbrandao** [comment]
Não vejo muita necessidade a não ser que seja para resolver algum problema de usabilidade... Mas, se você quiser propor algo, acho melhor fazer e mandar o PR e o pessoal avalia.

**Comment by MayogaX** [comment]
é que antes de fazer o PR precisava criar issue :p

**Comment by brenoferreira** [comment]
Alguma coisa que voce acha ruim hoje?

**Comment by egomesbrandao** [comment]
Algo que seria legal arrumar: o balão da descrição da palestra não fecha

**Comment by MayogaX** [comment]
Só acho o atual meio largado, muito cara de programador :p 

Mas então eu posso focar em coisas pequenas como a descrição de palestra como o Brandão citou

**Comment by egomesbrandao** [comment]
Não acho largado, acho eficiente para o que ele se propõe, mas não vejo por que não evoluir se alguém puder melhorá-lo. Essa correçãozinha que mecionei seria interessante.

**Comment by rodrigovidal** [comment]
@MayogaX Se você está com tempo para fazer isso, acho que seria ótimo uma repaginação. 

Por favor não deixe de tentar, fico no aguardo do PR :)

**Comment by FlaviaFortes** [comment]
Podia rolar de consertar o balãozinho que não fecha sem precisar mandar um PR com um layout todo novo para isso.  O que vocês acham? Isso dá pra fazer rapidinho.

**Comment by egomesbrandao** [comment]
Fique a vontade!

**Comment by brenoferreira** [comment]
@FlaviaFortes estou pensando em mudar o layout da grade de palestras. To pra fazer isso já tem um tempo (desde o DNAD do ano passado, admito). Se souber de algum layout legal ou quiser dar alguma ideia, será bem vinda qualquer ajuda

**Comment by brenoferreira** [comment]
Proposta de layout novo. Acho assim um pouco mais simples e fácil de ver o título e descrição das palestras. O que acham @egomesbrandao @rodrigovidal @MayogaX @FlaviaFortes ?

![screen shot 2015-05-09 at 20 56 59](https://cloud.githubusercontent.com/assets/707019/7552506/3a92a4f0-f68e-11e4-8e8f-9b327daeaa0b.png)
