### ISSUE TITLE
Publicar no Github Pages

### ISSUE THREAD

**Issue by brenoferreira** [dotnetarchitects/dnad#4]

**Comment by giggio** [comment]
Quem vai fazer esse?

**Comment by MayogaX** [comment]
acho que só o @egomesbrandao pode fazer pq precisa ter acesso as configurações do repositório, e ele é o único na organização da conta

**Comment by brenoferreira** [comment]
Eu posso fazer. Estava pensando em deletar tudo do branch `master` e manter todo o conteúdo no branch `gh-pages`.

**Comment by giggio** [comment]
Cria o branch `gh-pages` e apaga o branch `master`

``` bash
git checkout master
git checkout gh-pages
git branch -d master
git push origin gh-pages
git push origin :master
```
